# Classical Latin Text Collection Metadata Configuration

# Directory structure settings
base_directory: "lemmatized/"
file_extensions: [".txt"]

# Default values
defaults:
  language: "Latin"
  encoding: "utf-8"

# Individual works configuration
works:
  # Classical Period - Poetry
  - author: "Ovid"
    work: "Metamorphoses 1-2"
    work_short: "metamorphoses_1_2"
    period: "classical"
    genre: "poetry"
    subgenre: "epic"
    date_composed: "8 CE"
    books: 1
    file_pattern: "Ovid, Metamorphoses Books 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"
    
  - author: "Ovid"
    work: "Metamorphoses 3-5"
    work_short: "metamorphoses_3_5"
    period: "classical"
    genre: "poetry"
    subgenre: "mythological"
    date_composed: "8 CE"
    books: 1
    file_pattern: "Ovid, Metamorphoses Books 3-5.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - History  
  - author: "Livy"
    work: "Ab Urbe Condita 1-2"
    work_short: "ab_urbe_condita_1_2"
    period: "classical"
    genre: "history"
    subgenre: "annalistic"
    date_composed: "27-9 BCE"
    books: 1  # surviving books
    file_pattern: "Titus Livius (Livy), Ab urbe condita Books 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - History  
  - author: "Livy"
    work: "Ab Urbe Condita 3-4"
    work_short: "ab_urbe_condita_3_4"
    period: "classical"
    genre: "history"
    subgenre: "annalistic"
    date_composed: "27-9 BCE"
    books: 1  # surviving books
    file_pattern: "Titus Livius (Livy), Ab urbe condita Books 3-4.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - History  
  - author: "Livy"
    work: "Ab Urbe Condita 5-6"
    work_short: "ab_urbe_condita_5_6"
    period: "classical"
    genre: "history"
    subgenre: "annalistic"
    date_composed: "27-9 BCE"
    books: 1  # surviving books
    file_pattern: "Titus Livius (Livy), Ab urbe condita Books 5-6.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"
  
  # Classical Period - History  
  - author: "Caesar"
    work: "Commentarii de Bello Gallico 1-4"
    work_short: "bello_gallico_1_4"
    period: "classical"
    genre: "history"
    subgenre: "military_history"
    date_composed: "58-49 BCE"
    books: 1  # surviving books
    file_pattern: "Julius Caesar, Gallic War Books 1-4.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - History  
  - author: "Caesar"
    work: "Commentarii de Bello Gallico 5-8"
    work_short: "bello_gallico_5_8"
    period: "classical"
    genre: "history"
    subgenre: "military_history"
    date_composed: "58-49 BCE"
    books: 1  # surviving books
    file_pattern: "Julius Caesar, Gallic War Books 5-8.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - Oratory  
  - author: "Cicero"
    work: "Philippicae 1"
    work_short: "philippicae_1"
    period: "classical"
    genre: "oratory"
    subgenre: "condemnatory_speeches"
    date_composed: "44-43 BCE"
    books: 1  
    file_pattern: "Cicero, Marcus Tullius, Philippicae Speech 1.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - Oratory  
  - author: "Cicero"
    work: "Philippicae 2"
    work_short: "philippicae_2"
    period: "classical"
    genre: "oratory"
    subgenre: "condemnatory_speeches"
    date_composed: "44-43 BCE"
    books: 1  
    file_pattern: "Cicero, Marcus Tullius, Philippicae Speech 2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

  # Classical Period - Political Philosophy  
  - author: "Cicero"
    work: "De Republica 1-2"
    work_short: "republica_1_2"
    period: "classical"
    genre: "philosophy"
    subgenre: "dialogue"
    date_composed: "54-51 BCE"
    books: 1 
    file_pattern: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/Cicero, Marcus Tullius, De Republica Books 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

# Classical Period - Political Philosophy  
  - author: "Cicero"
    work: "De Republica 3-4"
    work_short: "republica_3_4"
    period: "classical"
    genre: "philosophy"
    subgenre: "dialogue"
    date_composed: "54-51 BCE"
    books: 1 
    file_pattern: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/Cicero, Marcus Tullius, De Republica Books 3-4.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

# Classical Period - Political Philosophy  
  - author: "Cicero"
    work: "De Republica 5-6"
    work_short: "republica_5_6"
    period: "classical"
    genre: "philosophy"
    subgenre: "dialogue"
    date_composed: "54-51 BCE"
    books: 1 
    file_pattern: "Cicero, Marcus Tullius, De Republica Books 5-6.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/classical/"

###############################################################################################

  # Imperial Period - Oratory
  - author: "Apuleius"
    work: "Apologia"
    work_short: "apologia"
    period: "imperial"
    genre: "oratory"
    subgenre: "defence"
    date_composed: "158-159 CE"
    books: 1
    file_pattern: "Apuleius, Apologia.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial/"

  # Imperial Period - Oratory
  - author: "Apuleius"
    work: "Florida"
    work_short: "florida"
    period: "imperial"
    genre: "oratory"
    subgenre: "lecture"
    date_composed: "160 CE"
    books: 1
    file_pattern: "Apuleius, Florida.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial/"

  # Imperial Period - Novel
  - author: "Apuleius"
    work: "The Golden Ass 1"
    work_short: "golden_ass_1"
    period: "imperial"
    genre: "novel"
    subgenre: "novel"
    date_composed: "~150-180 CE"
    books: 1
    file_pattern: "Apuleius, Metamorphoses Book 1.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial/"

  # Imperial Period - Novel
  - author: "Apuleius"
    work: "The Golden Ass 2"
    work_short: "golden_ass_2"
    period: "imperial"
    genre: "novel"
    subgenre: "novel"
    date_composed: "~150-180 CE"
    books: 1
    file_pattern: "Apuleius, Metamorphoses Book 2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial/"
    
  # Imperial Period - Philosophy
  - author: "Seneca"
    work: "Epistulae 1-15"
    work_short: "epistulae_1_15"
    period: "imperial"
    genre: "philosophy"
    subgenre: "letter"
    date_composed: "65 CE"
    books: 1  
    file_pattern: "Seneca, Lucius Annaeus, Epistulae 1-15.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Philosophy
  - author: "Seneca"
    work: "Epistulae 16-30"
    work_short: "epistulae_16_30"
    period: "imperial"
    genre: "philosophy"
    subgenre: "letter"
    date_composed: "65 CE"
    books: 1  
    file_pattern: "Seneca, Lucius Annaeus, Epistulae 16-30.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"
  
  # Imperial Period - Philosophy
  - author: "Seneca"
    work: "De Brevitate Vitae Ch. 1-20"
    work_short: "brevitate_vitae_ch1_20"
    period: "imperial"
    genre: "philosophy"
    subgenre: "essay"
    date_composed: "49 CE"
    books: 1
    file_pattern: "Seneca, Lucius Annaeus, de Brevitate Vitae Chapters 1-20.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Poetry
  - author: "Flaccus"
    work: "Argonautica 1"
    work_short: "argonautica_1"
    period: "imperial"
    genre: "poetry"
    subgenre: "mythological"
    date_composed: "70-90 CE"
    books: 1
    file_pattern: "Valerius Flaccus, Gaius, Argonautica Book 1.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Poetry
  - author: "Flaccus"
    work: "Argonautica 2"
    work_short: "argonautica_2"
    period: "imperial"
    genre: "poetry"
    subgenre: "mythological"
    date_composed: "70-90 CE"
    books: 1
    file_pattern: "Valerius Flaccus, Gaius, Argonautica Book 2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Poetry
  - author: "Flaccus"
    work: "Argonautica 3"
    work_short: "argonautica_3"
    period: "imperial"
    genre: "poetry"
    subgenre: "mythological"
    date_composed: "70-90 CE"
    books: 1
    file_pattern: "Valerius Flaccus, Gaius, Argonautica Book 3.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - History
  - author: "Tacitus"
    work: "Historiae 1-2"
    work_short: "historiae_1_2"
    period: "imperial"
    genre: "history"
    subgenre: "history"
    date_composed: "100-110 CE"
    books: 1
    file_pattern: "Tacitus, Cornelius, Historiae Books 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - History
  - author: "Tacitus"
    work: "Historiae 3-4"
    work_short: "historiae_3_4"
    period: "imperial"
    genre: "history"
    subgenre: "history"
    date_composed: "100-110 CE"
    books: 1
    file_pattern: "Tacitus, Cornelius, Historiae Books 3-4.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Treatise
  - author: "Saint Cyprian"
    work: "De Dominica Oratione 1-36"
    work_short: "dominica_oratione_1_36"
    period: "imperial"
    genre: "treatise"
    subgenre: "christianity"
    date_composed: "252 CE"
    books: 1
    file_pattern: "Cyprian Saint, Bishop of Carthage, De Dominica Oratione 1-36.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Theology
  - author: "Tertullian"
    work: "Ad Nationes II 1-2"
    work_short: "nationesii_1_2"
    period: "imperial"
    genre: "theology"
    subgenre: "defence"
    date_composed: "Late 100s-Early 200s CE"
    books: 1
    file_pattern: "Tertullian, Ad Nationes Libri Duo Books 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Theology
  - author: "Tertullian"
    work: "Apologeticum Ch. 1-20"
    work_short: "apologeticum_ch1_20"
    period: "imperial"
    genre: "theology"
    subgenre: "apology"
    date_composed: "197 CE"
    books: 1
    file_pattern: "Tertullian, Apologeticum Chapters 1-20.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

  # Imperial Period - Theology
  - author: "Tertullian"
    work: "Apologeticum Ch. 21-40"
    work_short: "apologeticum_ch21_40"
    period: "imperial"
    genre: "theology"
    subgenre: "apology"
    date_composed: "197 CE"
    books: 1
    file_pattern: "Tertullian, Apologeticum Chapters 21-40.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/imperial"

###############################################################################################

  # Late Period - Theology
  - author: "Augustine"
    work: "De Civitate Dei 1-2"
    work_short: "civitas_dei_1_2"
    period: "late"
    genre: "theology"
    subgenre: "apologetic"
    date_composed: "413-426 CE"
    books: 1
    file_pattern: "Augustine, De civitate dei Books 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

  # Late Period - Theology
  - author: "Augustine"
    work: "Epistulae 32"
    work_short: "epistulae_32"
    period: "late"
    genre: "letter"
    subgenre: "christianity"
    date_composed: "396-410 CE"
    books: 1
    file_pattern: "Augustine, Epistulae 32.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

#Disregarding confessiones right now because its autobiographical

  # Late Period - Theology
  - author: "Ambrose"
    work: "Exameron 1"
    work_short: "exameron_1"
    period: "late"
    genre: "theology"
    subgenre: "hexaemeral_literature"
    date_composed: "386-390 CE"
    books: 1
    file_pattern: "Ambrose, Saint, Bishop of Milan, Exameron Book 1.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

  # Late Period - Theology
  - author: "Ambrose"
    work: "Exameron 2"
    work_short: "exameron_2"
    period: "late"
    genre: "theology"
    subgenre: "hexaemeral_literature"
    date_composed: "386-390 CE"
    books: 1
    file_pattern: "Ambrose, Saint, Bishop of Milan, Exameron Book 2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

##Disregarding De Interpellatione because I have enough
##Disregarding Jerome for reason stated above
  
   # Late Period - Poetry
  - author: "Ausonius"
    work: "Mosella"
    work_short: "mosella"
    period: "late"
    genre: "poetry"
    subgenre: "poetry"
    date_composed: "370-371 CE"
    books: 1
    file_pattern: "Ausonius, Decimus Magnus, Mosella.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - Poetry
  - author: "Ausonius"
    work: "Ephemeris"
    work_short: "ephemeris"
    period: "late"
    genre: "poetry"
    subgenre: "poetry"
    date_composed: "367 CE"
    books: 1
    file_pattern: "Ausonius, Decimus Magnus, Ephemeris 1-8.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - Letter
  - author: "Ausonius"
    work: "Epistulae Ausonius 1-15"
    work_short: "epistulae_ausonius_1_15"
    period: "late"
    genre: "letter"
    subgenre: "letter"
    date_composed: "~360-395 CE"
    books: 1
    file_pattern: "Ausonius, Decimus Magnus, Epistulae 1-15.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - Poetry
  - author: "Ausonius"
    work: "Parentalia"
    work_short: "parentalia"
    period: "late"
    genre: "poetry"
    subgenre: "elegy"
    date_composed: "~380-395 CE"
    books: 1
    file_pattern: "Ausonius, Decimus Magnus, Parentalia 1-30.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

#Disregarding Ausonius, Oratio Versibus Rhopalicis

   # Late Period - Poetry
  - author: "Prudentius"
    work: "Psychomachia"
    work_short: "psychomachia"
    period: "late"
    genre: "poetry"
    subgenre: "christianity"
    date_composed: "348-405 CE"
    books: 1
    file_pattern: "Prudentius, Psychomachia 1.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - Poetry
  - author: "Prudentius"
    work: "Contra Orationem Symmachia 1-2"
    work_short: "orationem_symmachia_1_2"
    period: "late"
    genre: "poetry"
    subgenre: "apologetic"
    date_composed: "408-432 CE"
    books: 1
    file_pattern: "Prudentius, Contra Orationem Symmachia Book 1-2.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - History
  - author: "Marcellinus"
    work: "Res Gestae 14"
    work_short: "res_gestae_14"
    period: "late"
    genre: "history"
    subgenre: "biography"
    date_composed: "380-392 CE"
    books: 1
    file_pattern: "Ammianus Marcellinus, Res Gestae Book 14.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - History
  - author: "Marcellinus"
    work: "Res Gestae 15"
    work_short: "res_gestae_15"
    period: "late"
    genre: "history"
    subgenre: "biography"
    date_composed: "380-392 CE"
    books: 1
    file_pattern: "Ammianus Marcellinus, Res Gestae Book 15.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - History
  - author: "Marcellinus"
    work: "Res Gestae 16"
    work_short: "res_gestae_16"
    period: "late"
    genre: "history"
    subgenre: "biography"
    date_composed: "380-392 CE"
    books: 1
    file_pattern: "Ammianus Marcellinus, Res Gestae Book 16.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"

   # Late Period - History
  - author: "Marcellinus"
    work: "Res Gestae 17"
    work_short: "res_gestae_17"
    period: "late"
    genre: "history"
    subgenre: "biography"
    date_composed: "380-392 CE"
    books: 1
    file_pattern: "Ammianus Marcellinus, Res Gestae Book 17.txt"
    folder_path: "/workspaces/Latin-Semantic-Shift-Python/lemmatized/late"
    
